Vacation9/Models/ErrorViewModel.cs
namespace Vacation9.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Vacation9/ViewModels/HotelVM.cs
using Vacation9.Domains.Entities;

namespace Vacation9.ViewModels
{
    public class HotelVM
    {
        public string? NameHotel { get; set; }
        public int Stars { get; set; }
        public double Score { get; set; }
        public string? Benefit { get; set; }
        public string? Photo { get; set; }
        public string? City { get; set; }
        public CountryType Country { get; set; }
    }
}

Vacation9/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Vacation9.Models;

namespace Vacation9.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Vacation9/Controllers/HotelController.cs
using Microsoft.AspNetCore.Mvc;
using Vacation9.Domains.Data;
using Vacation9.Domains.Entities;
using Vacation9.Services.Interfaces;
using Vacation9.ViewModels;

namespace Vacation9.Controllers
{
    public class HotelController : Controller
    {
        private readonly IHotelService _hotelService;

        public HotelController(IHotelService hotelService)
        {
            _hotelService = hotelService;
        }

        public async Task<IActionResult> Index(CountryType country)
        {
            try
            {
                var hotels = await _hotelService.GetHotelsByCountryAsync(country);
                if (hotels != null)
                {
                    List<HotelVM> HotelVMs = new List<HotelVM>();
                    foreach (var hotel in hotels)
                    {
                        var hotelVM = new HotelVM();
                        hotelVM.NameHotel = hotel.NameHotel;
                        hotelVM.Photo = hotel.Photo;
                        hotelVM.Stars = hotel.Stars;
                        hotelVM.Score = hotel.Score;
                        hotelVM.Benefit = hotel.Benefit;
                        hotelVM.City = hotel.City;
                        hotelVM.Country = hotel.Country;
                        HotelVMs.Add(hotelVM);
                    }
                    return View(HotelVMs);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("","Fout bij het ophalen van de hotels: " + ex.Message);
            }
            return View();
        }
    }
}

Vacation9/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Vacation9/Views/Hotel/Index.cshtml
@model List<Vacation9.ViewModels.HotelVM>

@{
    ViewData["Title"] = "Index";

    var type = Model.FirstOrDefault()?.Country;

    string title = type switch
    {
        Vacation9.Domains.Entities.CountryType.Coast => "Lijst kust",
        Vacation9.Domains.Entities.CountryType.Wallonia => "Lijst ardennen",
        _ => "Lijst"
    };
}

<div class="indexCss">

<h1 class="hoofdTitel">@title</h1>
    <div class="containerTiles">
        @foreach (var hotel in Model)
        { 
            @await Html.PartialAsync("DisplayTemplates/_HotelTile", hotel)
        }
    </div>
</div>

Vacation9/Views/Shared/DisplayTemplates/_HotelTile.cshtml
@model Vacation9.ViewModels.HotelVM
    @if (Model != null)
    {
        <div class="tile">
            <div class="linkerkantTile">

                <h4 class="titelHotel">@Model.NameHotel</h4>

                <div class="imgHotel">
                    <img src="~/images/@Model.Photo" asp-append-version="true" alt="@Model.NameHotel" />
                    <div class="score">
                        @Model.Score
                    </div>
                </div>
            </div>


            <div class="rechterkantTile">

                <div class="sterren">
                    @for (int i=0; i<Model.Stars; i++)
                    {
                        <img src="~/images/star.jpg" />
                    }
                </div>

                <div class="buttons">
                    @* <input type="button" value="Foto's'" class="btnFoto"/>
                    <input type="button" value="Bewaren"/>
                    <input type="button" value="Video"/> *@
                    <a class="btnFoto">Foto's</a>
                    <a class="btnBewaren">Bewaren</a>
                    <a class="btnVideo">Video</a>
                </div>

                <div class="benefit">-@Model.Benefit</div>
            </div>
        </div>
    }

Vacation9/Views/Shared/_Footer.cshtml
<footer class="border-top footer text-muted">
    <div class="footerCss">
        <img src="~/images/TuiSmall.png" alt="TuiSmall" asp-append-version="true"/>
        - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

Vacation9/Views/Shared/_Header.cshtml
@using Vacation9.Domains.Entities;
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Vacation9</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Hotel" asp-action="Index" asp-route-country="@CountryType.Coast">Kust</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Hotel" asp-action="Index" asp-route-country="@CountryType.Wallonia">Ardennen</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

Vacation9/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vacation9</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Vacation9.styles.css" asp-append-version="true" />
</head>
<body>
    @await Html.PartialAsync("_Header")
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

       @await Html.PartialAsync("_Footer")
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>